# Generated by Django 4.2.2 on 2023-06-28 17:01

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefono', models.CharField(max_length=45)),
                ('FechaNacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('precio', models.FloatField()),
                ('cantidadEnInventario', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appExoticShoes.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPedido', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appExoticShoes.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('contraEntrega', 'Contra entrega'), ('PSE', 'PSE')], max_length=45)),
                ('monto', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(max_length=45, null=True)),
                ('pedidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appExoticShoes.pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicioEnvio', models.CharField(max_length=45)),
                ('DireccionEnv', models.CharField(max_length=45)),
                ('fechaEnvio', models.DateTimeField()),
                ('fechaEntrega', models.DateTimeField()),
                ('estado', models.CharField(max_length=45, null=True)),
                ('estadoPago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appExoticShoes.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDevolucion', models.DateTimeField(null=True)),
                ('motivo', models.CharField(max_length=200)),
                ('productosDevueltos', models.CharField(max_length=45, null=True)),
                ('cantidadDevuelta', models.IntegerField(null=True)),
                ('envio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appExoticShoes.envio')),
                ('pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appExoticShoes.pago')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appExoticShoes.pedidos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appExoticShoes.productos')),
            ],
        ),
    ]
