# Generated by Django 4.2.2 on 2023-06-22 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45, unique=True)),
                ('contraseña', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('FechaNacimiento', models.DateField(null=True)),
                ('direccion', models.CharField(max_length=45)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appExoticShoes.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('precio', models.FloatField()),
                ('cantidadEnInventario', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appExoticShoes.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPedido', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appExoticShoes.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('contraEntrega', 'Contra entrega'), ('PSE', 'PSE')], max_length=45)),
                ('monto', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(max_length=45, null=True)),
                ('pedidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appExoticShoes.pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicioEnvio', models.CharField(max_length=45)),
                ('DireccionEnv', models.CharField(max_length=45)),
                ('fechaEnvio', models.DateTimeField()),
                ('fechaEntrega', models.DateTimeField()),
                ('estado', models.CharField(max_length=45, null=True)),
                ('estadoPago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appExoticShoes.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDevolucion', models.DateTimeField(null=True)),
                ('motivo', models.CharField(max_length=200)),
                ('productosDevueltos', models.CharField(max_length=45, null=True)),
                ('cantidadDevuelta', models.IntegerField(null=True)),
                ('envio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appExoticShoes.envio')),
                ('pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appExoticShoes.pago')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appExoticShoes.pedidos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appExoticShoes.productos')),
            ],
        ),
    ]
