# Generated by Django 4.2.3 on 2023-09-21 02:56

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefono', models.CharField(max_length=45)),
                ('fechaNacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=45)),
                ('fotoPerfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tallas', to='appExoticShoes.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoPedido', models.CharField(max_length=45, unique=True)),
                ('fechaPedido', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estadoPedido', models.CharField(default='pendiente', max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('tarjetaCredito', 'Tarjeta de Credito'), ('tarjetaDebito', 'Tarjeta de Debito'), ('contraEntrega', 'Contra entrega'), ('PSE', 'Pago Seguro en Linea(PSE)')], max_length=45)),
                ('fechaPago', models.DateTimeField()),
                ('estadoPago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=45)),
                ('confirmado', models.BooleanField(default=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccionEntrega', models.CharField(max_length=255)),
                ('codigoPostal', models.CharField(max_length=45)),
                ('ciudad', models.CharField(max_length=45)),
                ('departamento', models.CharField(max_length=45)),
                ('pais', models.CharField(max_length=45)),
                ('costoEnvio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estadoEnvio', models.CharField(default='pendiente', max_length=50)),
                ('fechaEstimadaEntrega', models.DateField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fechaDevolucion', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.producto')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.talla')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.producto')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='appExoticShoes.CartItem', to='appExoticShoes.producto'),
        ),
    ]
