# Generated by Django 4.2.2 on 2023-06-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('appExoticShoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='grupos',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
