# Generated by Django 4.2.3 on 2023-09-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appExoticShoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talla',
            old_name='nombre',
            new_name='talla',
        ),
    ]
