# Generated by Django 4.2.2 on 2023-06-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExoticShoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
