# Generated by Django 4.2.3 on 2023-09-07 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appExoticShoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tallas',
            field=models.ManyToManyField(to='appExoticShoes.talla'),
        ),
        migrations.AlterField(
            model_name='devolucione',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estadoPedido',
            field=models.CharField(default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='talla',
            name='nombre',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('unica', 'Unica')], max_length=5),
        ),
        migrations.DeleteModel(
            name='ProductoConTalla',
        ),
    ]
