# Generated by Django 4.2.3 on 2023-09-07 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appExoticShoes', '0002_producto_tallas_alter_devolucione_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='existencias',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.producto')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.talla')),
            ],
            options={
                'unique_together': {('producto', 'talla')},
            },
        ),
    ]
