# Generated by Django 4.2.3 on 2023-07-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExoticShoes', '0002_usuarios_grupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Borrado')], default=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
