# Generated by Django 4.2.3 on 2023-08-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appExoticShoes', '0005_itemcarrito_subtotal_itemcarrito_total_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos',
            options={'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterUniqueTogether(
            name='pedidos',
            unique_together={('fechaPedido', 'usuario')},
        ),
    ]
