# Generated by Django 4.2.3 on 2023-08-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appExoticShoes', '0006_alter_pedidos_options_alter_pedidos_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='pedidos',
            unique_together=set(),
        ),
    ]
