# Generated by Django 4.2.3 on 2023-08-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appExoticShoes', '0007_alter_pedidos_options_alter_pedidos_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='grupos',
        ),
    ]
