# Generated by Django 4.2.3 on 2023-08-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appExoticShoes', '0009_cart_cartitem_delete_itemcarrito_cart_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.categorias'),
        ),
    ]
