# Generated by Django 4.2.3 on 2023-08-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appExoticShoes', '0011_rename_categorias_categoria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devoluciones',
            new_name='Devolucione',
        ),
        migrations.RenameModel(
            old_name='Pedidos',
            new_name='Pedido',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appExoticShoes.usuario'),
        ),
    ]
