# Generated by Django 4.2.3 on 2023-09-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appExoticShoes', '0013_alter_cart_user_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidadEnInventario',
            new_name='existencias',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='FechaNacimiento',
            new_name='fechaNacimiento',
        ),
    ]
