# Generated by Django 4.2.3 on 2023-09-04 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appExoticShoes', '0014_rename_cantidadeninventario_producto_existencias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigoPedido',
            field=models.CharField(default=0, max_length=45, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.pedido'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.producto'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appExoticShoes.usuario'),
        ),
    ]
