# Generated by Django 4.2.3 on 2023-09-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExoticShoes', '0015_pedido_codigopedido_pedido_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigoPedido',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.FloatField(),
        ),
    ]
